# Generated by Django 4.1.13 on 2024-04-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_fdaccountmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fdaccountmodel',
            table='fd_accounts',
        ),
    ]
