# Generated by Django 4.1.13 on 2024-04-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_fdaccountmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDAccountModel',
            fields=[
                ('rd_ac_no', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opening_date', models.DateField()),
                ('int_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rd_mat_date', models.DateField(null=True)),
                ('rd_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pre_mature_withdraw', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=255)),
                ('renew', models.IntegerField()),
                ('personal_ac_no', models.IntegerField()),
                ('rd_months', models.IntegerField()),
                ('mat_amt', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'rd_accounts',
            },
        ),
    ]
