# Generated by Django 4.1.13 on 2024-05-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_rdaccountmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdaccountmodel',
            name='int_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
