# Generated by Django 4.1.13 on 2024-12-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_rename_emi_fdloan_emi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fdloan',
            old_name='Customer_Name',
            new_name='customer_name',
        ),
        migrations.RemoveField(
            model_name='fdloan',
            name='fd_amount',
        ),
        migrations.RemoveField(
            model_name='fdloan',
            name='loan_account_number',
        ),
        migrations.RemoveField(
            model_name='fdloan',
            name='username',
        ),
        migrations.AddField(
            model_name='fdloan',
            name='id',
            field=models.BigAutoField(auto_created=True, default='null', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
